name: build
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node.js environment
        uses: actions/setup-node@main
        with:
          node-version: lts

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
