name: playwright tests
on: [push, pull_request]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node.js environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run playwright tests
        run: pnpm exec playwright test

      - name: Upload playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
